server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:dev-secret-key-minimum-256-bits-long-replace-in-production-env}
jwt.access-expiry-ms=900000
jwt.refresh-expiry-ms=604800000

verification.code-expiry-minutes=${VERIFICATION_CODE_EXPIRY_MINUTES:10}
mail.from=${MAIL_FROM:no-reply@marketplace.local}

spring.mail.host=${SMTP_HOST:host.docker.internal}
spring.mail.port=${SMTP_PORT:2525}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:false}

seller.service.url=${SELLER_SERVICE_URL:http://localhost:8084}
