services:
  auth-service:
    build: ./auth-service
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/auth_db
      DB_USER: postgres
      DB_PASS: admin
      JWT_SECRET: dev-secret-key-minimum-256-bits-long-replace-in-production-env
    networks:
      - internal

  catalog-service:
    build: ./catalog-service
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/catalog_db
      DB_USER: postgres
      DB_PASS: admin
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: product-images
      ORDER_SERVICE_URL: http://order-service:8083
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - minio
      - auth-service
      - order-service
    networks:
      - internal

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - internal

  order-service:
    build: ./order-service
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/order_db
      DB_USER: postgres
      DB_PASS: admin
      CATALOG_SERVICE_URL: http://catalog-service:8082
    depends_on:
      - catalog-service
    networks:
      - internal

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: dev-secret-key-minimum-256-bits-long-replace-in-production-env
      AUTH_SERVICE_URL: http://auth-service:8081
      CATALOG_SERVICE_URL: http://catalog-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
      SELLER_SERVICE_URL: http://seller-service:8084
      ANALYTICS_SERVICE_URL: http://analytics-service:8085
      AI_CHAT_SERVICE_URL: http://ai-chat-service:8086
    depends_on:
      - auth-service
      - catalog-service
      - order-service
    networks:
      - internal

volumes:
  minio-data:

networks:
  internal:
