services:
  auth-service:
    build: ./auth-service
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/auth_db
      DB_USER: postgres
      DB_PASS: admin
      JWT_SECRET: dev-secret-key-minimum-256-bits-long-replace-in-production-env
    networks:
      - internal

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: dev-secret-key-minimum-256-bits-long-replace-in-production-env
      AUTH_SERVICE_URL: http://auth-service:8081
      CATALOG_SERVICE_URL: http://catalog-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
      SELLER_SERVICE_URL: http://seller-service:8084
      ANALYTICS_SERVICE_URL: http://analytics-service:8085
      AI_CHAT_SERVICE_URL: http://ai-chat-service:8086
    depends_on:
      - auth-service
    networks:
      - internal

networks:
  internal:
